alias: PIR Living Room On
trigger:
   platform: state
   entity_id: binary_sensor.sensor_2
   to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.motion_sensors
    state: 'on' 
  - condition: state
    entity_id: input_select.house_mode
    state: 'Home'
  - condition: state
    entity_id: input_select.living_room_mode
    state: 'Idle'
 
action:
   service: light.turn_on
   data:
     entity_id: light.living_room
    # brightness: 155
    # rgb_color: [255,153,102]