- !include automation/motion_on_lr.yaml
- !include automation/motion_off_lr.yaml
- !include automation/motion_on_sleep_lr.yaml
- !include automation/motion_on_br.yaml
- !include automation/motion_off_br.yaml
- !include automation/motion_on_hall.yaml
- !include automation/motion_off_hall.yaml
- !include automation/motion_on_sleep_hall.yaml
#- !include automation/motion_lr.yaml #depracted
- !include automation/redalert.yaml
- !include automation/media_playing_tv.yaml
- !include automation/media_stopped_tv.yaml
- !include automation/media_lights_on.yaml
- !include automation/media_lights_off.yaml
- !include automation/kodi_playing_channel_change.yaml
- !include automation/bedroom_cc_play.yaml
- !include automation/bedroom_cc_stop.yaml
- !include automation/kitchen_cc_play.yaml
- !include automation/kitchen_cc_stop.yaml
- !include automation/morning_alarm.yaml
- !include automation/update_kodi.yaml
- !include automation/bedtime_set.yaml
- !include automation/a_home_announce.yaml
- !include automation/nobodys_home.yaml
- !include automation/away_set.yaml
- !include automation/identify.yaml
- !include automation/wall_panel_off.yaml
- !include automation/start_id_scan.yaml
- !include automation/z550_vol_change_up.yaml
- !include automation/z550_vol_change_down.yaml
- !include automation/ps3_on_channelChange.yaml
- !include automation/motion/motion_on_kitchen.yaml
- !include automation/motion/motion_off_kitchen.yaml
