alias: 'bedtime scenatio Lights'
hide_entity: True
trigger:
  platform: state
  entity_id: input_select.house_mode
  to: "Sleep"

action:
    
#set lights for home sceario
  - service: light.turn_on
    data:
      entity_id: light.living_room
      brightness: 50
      rgb_color: [255,0,0]
  - service: hue.hue_activate_scene
    data: 
       group_name: "Kitchen"
       scene_name: "Nightlight"
  - service: hue.hue_activate_scene
    data: 
       group_name: "Bathroom"
       scene_name: "Nightlight"
       
  - service: light.turn_off
    data:
      entity_id: group.all_lights
      
  - service: media_player.turn_off
    entity_id: media_player.all
      
  - service: media_player.turn_off
    entity_id: media_player.living_room_tv
        
  - service: light.turn_on
    data:
      entity_id: 
        - light.bedroom
          #- light.living_room
      brightness: 255
        
  - service: light.turn_off
    data:
      entity_id: 
         - light.bedroom
          #- light.living_room
      transition: 300
        
  - service: input_boolean.turn_on
    entity_id: input_boolean.motion_sensors