alias: "Bedroom ChromeCast Playing"
trigger:
  - platform: state
    entity_id: media_player.bedroom_speaker
    to: 'playing'
  - platform: state
    entity_id: media_player.all
    to: 'playing'
    
action:

   - service: switch.turn_on
     entity_id: switch.bedroom_amp
