alias: "Bedroom ChromeCast Stopped"
trigger:
  - platform: state
    entity_id: media_player.bedroom_speaker
    to: 'off'
    for:
      minutes: 5
  - platform: state
    entity_id: media_player.all
    to: 'off'
    for:
      minutes: 5
action:

   - service: switch.turn_off
     entity_id: switch.bedroom_amp
