alias: "TV Media Player Started"
trigger:
  - platform: state
    entity_id: media_player.kodi
    to: 'playing'
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
    
action:
    - service: input_select.select_option
      data:
        entity_id: input_select.living_room_mode
        option: 'Watching Media'